### ISSUE TITLE
Set up automatic processing of record linkage suggestions

### ISSUE THREAD

**Issue by fricklerhandwerk** [Nix-Security-WG/nix-security-tracker#221]
For security team members to be able to triage effectively, we need pre-computed suggestions for record linkage:

- As new CVEs are ingested, match them with existing derivations.
- As new derivations are ingested, match them with untriaged CVEs.

Open questions:
- Should newly ingested items also be proposed for getting added to existing linked records?

**Comment by RaitoBezarius** [comment]
Matching a new derivation with untriaged CVE is touchy because our CVE database can go back to 1999. This deserves a bit more thought to do it properly and not dealing with it doesn't reduce the problem because the way we care the most is: we already have the derivation ingested and we have a new CVE.

It's pretty rare to introduce a _new_ derivation for which we already have a CVE in (except for historical open CVEs, which can be dealt with a one-time matching).
